apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cryosparcm.fullname" . }}
  labels:
    {{- include "cryosparcm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cryosparcm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cryosparcm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cryosparcm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["cryosparcm","start"]
          ports:
            - name: http
              containerPort: 39000
              protocol: TCP
            - name: mongodb
              containerPort: 39001
              protocol: TCP
            - name: core
              containerPort: 39002
              protocol: TCP
            - name: vis
              containerPort: 39003
              protocol: TCP
            - name: rtp
              containerPort: 39005
              protocol: TCP
            - name: api
              containerPort: 39006
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "cryosparcm.volumeMounts" . |nindent 12 }}
            - mountPath: /cryosparc_master/run
              name: cryosparc-run
            - mountPath: /cryosparc_database
              name: cryosparc-mongodb
            - mountPath: /home/cryosparc
              name: cryosparc-home
        {{- range .Values.logs }}
        - name: log-{{ . |replace "_" "-" }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: busybox
          command: ["sh","-c"]
          args:
            - |
              exec tail -F -n1000 /cryosparc_master/run/{{ . }}.log
          volumeMounts:
            - mountPath: /cryosparc_master/run
              name: cryosparc-run
              readOnly: true
        {{- end }}
      initContainers:
        - name: init-cryosparcuser
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: busybox
          command: ["sh","-c"]
          args:
            - |
              HOME="/home/cryosparc"
              SSH_KEY="/k8s-secrets/id.key"
              [ -d ${HOME}/.ssh ] || { mkdir -p ${HOME}/.ssh; chmod 0700 ${HOME}/.ssh; }
              [ -f ${HOME}/.ssh/id_ed25519 ] || { cp $SSH_KEY ${HOME}/.ssh/id_ed25519; chmod 0400 ${HOME}/.ssh/id_ed25519; }
          volumeMounts:
            - mountPath: /home/cryosparc
              name: cryosparc-home
            - mountPath: /k8s-secrets/
              name: cryosparc-ssh
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- include "cryosparcm.volumes" . |nindent 8 }}
        - name: cryosparc-run
          emptyDir:
            sizeLimit: 500Mi
        - name: cryosparc-home
          emptyDir:
            sizeLimit: 500Mi
        - name: cryosparc-mongodb
          persistentVolumeClaim:
            claimName: {{ include "cryosparcm.fullname" . }}-mongodb
        - name: cryosparc-ssh
          secret:
            secretName: {{ .Values.ssh_secret.name }}
            items:
              - key: {{ .Values.ssh_secret.key }}
                path: id.key
