apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cryosparcm.fullname" . }}-mongodb
  labels:
    {{- include "cryosparcm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: microk8s-hostpath
  selector: {}
