apiVersion: v1
kind: Service
metadata:
  name: {{ include "cryosparcm.fullname" . }}
  labels:
    {{- include "cryosparcm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ add $.Values.service.port 1 }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
    - port: {{ add $.Values.service.port 2 }}
      targetPort: core
      protocol: TCP
      name: core
    - port: {{ add $.Values.service.port 3 }}
      targetPort: vis
      protocol: TCP
      name: vis
    - port: {{ add $.Values.service.port 5 }}
      targetPort: rtp
      protocol: TCP
      name: rtp
    - port: {{ add $.Values.service.port 6 }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "cryosparcm.selectorLabels" . | nindent 4 }}
