apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cryosparc.fullname" . }}
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
data:
  passwd: |
    {{- .Files.Get "files/passwd" |nindent 4 }}
    cryosparc:x:{{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.runAsGroup }}::/home/cryosparc:/usr/sbin/nologin
  group: |
    {{- .Files.Get "files/group" |nindent 4 }}
    cryosparc:x:{{ .Values.podSecurityContext.runAsGroup }}:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cryosparc.fullname" . }}w
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
data:
  passwd: |
    {{- .Files.Get "files/passwd" |nindent 4 }}
    cryosparc:x:{{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.runAsGroup }}::/home/cryosparc:/bin/sh
