apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cryosparc.fullname" . }}
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.master.autoscaling.enabled }}
  replicas: {{ .Values.master.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cryosparc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.master.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cryosparc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.master.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cryosparc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - {{ include "cryosparc.fullname" . }}m
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.master.image.repository }}:{{ .Values.master.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.master.image.pullPolicy }}
          args: ["cryosparcm","start"]
          ports:
            - {name: http, containerPort: 39000, protocol: TCP}
            - {name: mongodb, containerPort: 39001, protocol: TCP}
            - {name: core, containerPort: 39002, protocol: TCP}
            - {name: vis, containerPort: 39003, protocol: TCP}
            - {name: rtp, containerPort: 39005, protocol: TCP}
            - {name: api, containerPort: 39006, protocol: TCP}
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.master.resources | nindent 12 }}
          volumeMounts:
            {{- include "cryosparc.master.volumeMounts" . |nindent 12 }}
            - mountPath: /cryosparc_master/run
              name: cryosparc-run
            - mountPath: /cryosparc_database
              name: cryosparc-mongodb
            {{- range .Values.volumes }}
            - mountPath: {{ .path }}
              name: {{ .name }}
            {{- end }}
        - name: sync-users
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ .Values.master.image.repository }}:{{ .Values.master.image.tag | default .Chart.AppVersion }}"
          args: ["cryosparcm-sync-user"]
          env:
            - {name: PYTHONUNBUFFERED, value: "1"}
            - name: CRYOSPARCM_UUID_EMAIL
              value: {{ .Values.master.admin.email }}
            - name: CRYOSPARCM_CHECKSUM_USERS
              value: {{ include (print $.Template.BasePath "/master/secret-users.yaml") . | sha256sum }}
          volumeMounts:
            {{- include "cryosparc.master.volumeMounts" . |nindent 12 }}
            - mountPath: /k8s-secrets/user-acct
              name: cryosparc-users
              readOnly: true
        {{- range .Values.master.logs }}
        - name: log-{{ . |replace "_" "-" }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: busybox
          command: ["sh","-c"]
          args:
            - |
              exec tail -F -n1000 /cryosparc_master/run/{{ . }}.log
          volumeMounts:
            - mountPath: /cryosparc_master/run
              name: cryosparc-run
              readOnly: true
        {{- end }}
      initContainers:
        - name: init-cryosparcuser
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: busybox
          command: ["sh","-c"]
          args:
            - |
              HOME="/home/cryosparc"
              SSH_KEY="/k8s-secrets/id.key"
              [ -d "${HOME}" ] || { mkdir -p "${HOME}"; chmod 0700 "${HOME}"; }
              [ -d "${HOME}/.ssh" ] || { mkdir -p "${HOME}/.ssh"; chmod 0700 "${HOME}/.ssh"; }
              [ -f "${HOME}/.ssh/id_ed25519" ] || { cp "${SSH_KEY}" "${HOME}/.ssh/id_ed25519"; chmod 0400 "${HOME}/.ssh/id_ed25519"; }
          volumeMounts:
            - mountPath: /home
              name: cryosparc-home
            - mountPath: /k8s-secrets/
              name: cryosparc-ssh
              readOnly: true
      {{- with .Values.master.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.master.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.master.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- include "cryosparc.master.volumes" . |nindent 8 }}
        - name: cryosparc-run
          emptyDir:
            sizeLimit: 500Mi
        - name: cryosparc-mongodb
          persistentVolumeClaim:
            claimName: {{ include "cryosparc.fullname" . }}-mongodb
        - name: cryosparc-ssh
          secret:
            secretName: {{ .Values.ssh_secret.name }}
            items:
              - key: {{ .Values.ssh_secret.keys.private }}
                path: id.key
        - name: cryosparc-users
          secret:
            secretName: {{ include "cryosparc.fullname" . }}-users
        {{- range .Values.volumes }}
        {{- if (hasKey . "ephemeral") }}
        - name: {{ .name }}
          ephemeral:
            {{- toYaml .ephemeral | nindent 12 }}
        {{- else }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ default (printf "%s-%s" $.Release.Name .name) .persistenVolumeClaimName }}
        {{- end }}
        {{- end }}
