apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryosparc.fullname" . }}-users
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
stringData:
  values-users.csv: |
    email,password,admin,username,firstname,lastname
    {{- range .Values.master.user.users }}
    {{ .email }},
    {{- .password |default ""}},
    {{- .admin |default false |ternary "True" "False" }},
    {{- .username |default .email}},
    {{- .firstname |default "" }},
    {{- .lastname |default "" }}
    {{- end }}
