apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryosparc.fullname" . }}
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
stringData:
  config.sh: |
    # {{ .Template.Name }}
    # Instance Configuration
    export CRYOSPARC_LICENSE_ID="{{ .Values.license_id }}"
    export CRYOSPARC_MASTER_HOSTNAME="{{ .Values.master.hostname |default (printf "%s%s" (include "cryosparc.fullname" .) "m") }}"
    export CRYOSPARC_DB_PATH="/cryosparc_database"
    export CRYOSPARC_BASE_PORT=39000
    export CRYOSPARC_DB_CONNECTION_TIMEOUT_MS=20000

    # Security
    export CRYOSPARC_INSECURE=false
    export CRYOSPARC_DB_ENABLE_AUTH=true

    # Cluster Integration
    export CRYOSPARC_CLUSTER_JOB_MONITOR_INTERVAL=10
    export CRYOSPARC_CLUSTER_JOB_MONITOR_MAX_RETRIES=1000000

    # Project Configuration
    export CRYOSPARC_PROJECT_DIR_PREFIX='CS-'

    # Development
    export CRYOSPARC_DEVELOP=false

    # Other
    export CRYOSPARC_CLICK_WRAP=true
    export CRYOSPARC_MONGO_EXTRA_FLAGS=""

    # Docker buildx
    export CRYOSPARC_FORCE_HOSTNAME=true
    export CRYOSPARC_FORCE_USER=true
  users: |
    {{- range .Values.master.users }}
    |{{ .email }}|{{ .username |default .email}}|{{ .firstname |default "" }}|{{ .lastname |default "" }}|{{ .password |default ""}}|
    {{- end }}
