apiVersion: v1
kind: Service
metadata:
  name: {{ include "cryosparc.fullname" . }}m
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
spec:
  {{- with .Values.master.service }}
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ add .port 1 }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
    - port: {{ add .port 2 }}
      targetPort: core
      protocol: TCP
      name: core
    - port: {{ add .port 3 }}
      targetPort: vis
      protocol: TCP
      name: vis
    - port: {{ add .port 5 }}
      targetPort: rtp
      protocol: TCP
      name: rtp
    - port: {{ add .port 6 }}
      targetPort: api
      protocol: TCP
      name: api
  {{- end }}
  selector:
    {{- include "cryosparc.selectorLabels" . | nindent 4 }}
