{{- if ne .Values.master.workload_resource "StatefulSet" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cryosparc.fullname" . }}-mongodb
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
spec:
  {{- with .Values.master.mongodb.volume }}
  accessModes:
    {{- .accessModes |toYaml |nindent 4 }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .size }}
  {{- include "cryosparc.storageClassName" (dict "vol" . "global" $.Values.global) |nindent 2 }}
  {{- if .selector }}
  selector:
    {{ .selector |toYaml |nindent 4 }}
  {{- end }}
  {{- end }}
{{- end -}}
{{- range .Values.volumes }}
{{- if not (hasKey . "ephemeral") }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cryosparc.fullname" $ }}-{{ .name }}
  labels:
    {{- include "cryosparc.labels" $ | nindent 4 }}
spec:
  accessModes:
    {{- default (list "ReadWriteMany") .accessModes |toYaml |nindent 4 }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .size }}
  {{- include "cryosparc.storageClassName" (dict "vol" . "global" $.Values.global) |nindent 2 }}
  {{- if .selector }}
  selector:
    {{- default "{}" .selector |toYaml |nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
