---
# charts/omero-server/templates/configmap.yaml
# https://docs.openmicroscopy.org/omero/5.6.3/sysadmins/config.html
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omero-server.fullname" . }}
  labels:
    {{- include "omero-server.labels" . | nindent 4 }}
data:
  00kubernetes-configmap.omero: |
{{- with .Values.omero }}
    omero.checksum.supported={{.checksum.supported}}
    omero.data.dir={{.data.dir}}
    omero.managed.dir={{.managed.dir}}
{{- with .db }}
    omero.db.authority={{.authority}}
    omero.db.dialect={{.dialect}}
    omero.db.driver={{.driver}}
    omero.db.patch={{.patch}}
    omero.db.poolsize={{.poolsize}}
    omero.db.prepared_statement_cache_size={{.prepared_statement_cache_size}}
    omero.db.profile={{.profile}}
    omero.db.sql_action_class={{.sql_action_class}}
    omero.db.statistics={{.statistics}}
    omero.db.version={{.version}}
{{- end }}
{{- with .glacier2.IceSSL }}
    omero.glacier2.IceSSL.CAs={{.CAs}}
    omero.glacier2.IceSSL.CertFile={{.CertFile}}
    omero.glacier2.IceSSL.Ciphers={{.Ciphers}}
    omero.glacier2.IceSSL.DefaultDir={{.DefaultDir}}
    omero.glacier2.IceSSL.Password={{.Password}}
    omero.glacier2.IceSSL.ProtocolVersionMax={{.ProtocolVersionMax}}
    omero.glacier2.IceSSL.Protocols={{.Protocols}}
{{- end }}
{{- end }}
