---
# https://docs.openmicroscopy.org/omero/5.6.3/sysadmins/config.html
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omero-server.fullname" . }}
  labels:
    {{- include "omero-server.labels" . | nindent 4 }}
data:
  00kubernetes-configmap.omero: |
{{- with .Values.omero }}
    config set omero.checksum.supported {{.checksum.supported|squote}}
    config set omero.data.dir {{.data.dir|squote}}
{{- with .fs.repo }}
    config set omero.fs.repo.path {{.path|squote}}
    config set omero.fs.repo.path_rules {{.path_rules|squote}}
{{- end }}
    config set omero.managed.dir {{.managed.dir|squote}}
{{- with .client }}
    config set omero.client.browser.thumb_default_size {{.browser.thumb_default_size|squote}}
    config set omero.client.download_as.max_size {{.download_as.max_size|toJson|squote}}
    config set omero.client.icetransports {{.icetransports}}
    config set omero.client.scripts_to_ignore {{.scripts_to_ignore|squote}}
    config set omero.client.ui.menu.dropdown.colleagues.enabled {{.ui.menu.dropdown.colleagues.enabled|squote}}
    config set omero.client.ui.menu.dropdown.colleagues.label {{.ui.menu.dropdown.colleagues.label|squote}}
    config set omero.client.ui.menu.dropdown.everyone.enabled {{.ui.menu.dropdown.everyone.enabled|squote}}
    config set omero.client.ui.menu.dropdown.everyone.label {{.ui.menu.dropdown.everyone.label|squote}}
    config set omero.client.ui.menu.dropdown.leaders.enabled {{.ui.menu.dropdown.leaders.enabled|squote}}
    config set omero.client.ui.menu.dropdown.leaders.label {{.ui.menu.dropdown.leaders.label|squote}}
    config set omero.client.ui.tree.orphans.description {{.ui.tree.orphans.description|squote}}
    config set omero.client.ui.tree.orphans.enabled {{.ui.tree.orphans.enabled|squote}}
    config set omero.client.ui.tree.orphans.name {{.ui.tree.orphans.name|squote}}
    config set omero.client.ui.tree.orphans.type_order {{.ui.tree.orphans.type_order|squote}}
    config set omero.client.viewer.initial_zoom_level {{.viewer.initial_zoom_level|squote}}
    config set omero.client.viewer.interpolate_pixels {{.viewer.interpolate_pixels|squote}}
    config set omero.client.viewer.roi_limit {{.viewer.roi_limit|squote}}
    config set omero.client.web.host {{.web.host|squote}}
{{- end }}
{{- with .db }}
    config set omero.db.authority {{.authority|squote}}
    config set omero.db.dialect {{.dialect|squote}}
    config set omero.db.driver {{.driver|squote}}
    config set omero.db.patch {{.patch|squote}}
    config set omero.db.poolsize {{.poolsize|squote}}
    config set omero.db.prepared_statement_cache_size {{.prepared_statement_cache_size|squote}}
    config set omero.db.profile {{.profile|squote}}
    config set omero.db.sql_action_class {{.sql_action_class|squote}}
    config set omero.db.statistics {{.statistics|squote}}
    config set omero.db.version {{.version|squote}}
{{- end }}
{{- with .glacier2.IceSSL }}
    config set omero.glacier2.IceSSL.CAs {{.CAs|squote}}
    config set omero.glacier2.IceSSL.CertFile {{.CertFile|squote}}
    config set omero.glacier2.IceSSL.Ciphers {{.Ciphers|squote}}
    config set omero.glacier2.IceSSL.DefaultDir {{.DefaultDir|squote}}
    config set omero.glacier2.IceSSL.Password {{.Password|squote}}
    config set omero.glacier2.IceSSL.ProtocolVersionMax {{.ProtocolVersionMax|squote}}
    config set omero.glacier2.IceSSL.Protocols {{.Protocols|squote}}
{{- end }}
{{- end }}
