---
# charts/omero-server/templates/configmap.yaml
# https://docs.openmicroscopy.org/omero/5.6.3/sysadmins/config.html
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omero-server.fullname" . }}
  labels:
    {{- include "omero-server.labels" . | nindent 4 }}
data:
  00kubernetes-configmap.omero: |
    {{- include "omero.config" (dict "omero" .Values.omero "omero_cfg" list) | nindent 4 }}
