---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omero-server.fullname" . }}
  labels:
    {{- include "omero-server.labels" . | nindent 4 }}
data:
  omero.configmap: |
{{- with .Values.omero }}
    omero.checksum.supported {{.checksum.supported|quote}}
    omero.data.dir {{.data.dir|quote}}
{{- with .fs.repo }}
    omero.fs.repo.path {{.path|quote}}
    omero.fs.repo.path_rules {{.path_rules|quote}}
{{- end }}
    omero.managed.dir {{.managed.dir|quote}}
{{- with .client }}
    omero.client.browser.thumb_default_size {{.browser.thumb_default_size|quote}}
    omero.client.download_as.max_size {{.download_as.max_size|toJson|quote}}
    omero.client.icetransports {{.icetransports}}
    omero.client.scripts_to_ignore {{.scripts_to_ignore|quote}}
    omero.client.ui.menu.dropdown.colleagues.enabled {{.ui.menu.dropdown.colleagues.enabled|quote}}
    omero.client.ui.menu.dropdown.colleagues.label {{.ui.menu.dropdown.colleagues.label|quote}}
    omero.client.ui.menu.dropdown.everyone.enabled {{.ui.menu.dropdown.everyone.enabled|quote}}
    omero.client.ui.menu.dropdown.everyone.label {{.ui.menu.dropdown.everyone.label|quote}}
    omero.client.ui.menu.dropdown.leaders.enabled {{.ui.menu.dropdown.leaders.enabled|quote}}
    omero.client.ui.menu.dropdown.leaders.label {{.ui.menu.dropdown.leaders.label|quote}}
    omero.client.ui.tree.orphans.description {{.ui.tree.orphans.description|quote}}
    omero.client.ui.tree.orphans.enabled {{.ui.tree.orphans.enabled|quote}}
    omero.client.ui.tree.orphans.name {{.ui.tree.orphans.name|quote}}
    omero.client.ui.tree.orphans.type_order {{.ui.tree.orphans.type_order|quote}}
    omero.client.viewer.initial_zoom_level {{.viewer.initial_zoom_level|quote}}
    omero.client.viewer.interpolate_pixels {{.viewer.interpolate_pixels|quote}}
    omero.client.viewer.roi_limit {{.viewer.roi_limit|quote}}
    omero.client.web.host {{.web.host|quote}}
{{- end }}
{{- with .db }}
    omero.db.authority {{.authority|quote}}
    omero.db.dialect {{.dialect|quote}}
    omero.db.driver {{.driver|quote}}
    omero.db.patch {{.patch|quote}}
    omero.db.poolsize {{.poolsize|quote}}
    omero.db.prepared_statement_cache_size {{.prepared_statement_cache_size|quote}}
    omero.db.profile {{.profile|quote}}
    omero.db.sql_action_class {{.sql_action_class|quote}}
    omero.db.statistics {{.statistics|quote}}
    omero.db.version {{.version|quote}}
{{- end }}
{{- end }}
