---
# https://www.postgresql.org/docs/current/libpq-envars.html
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "omero-server.fullname" . }}-db-migration
  labels:
    {{- include "omero-server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "omero-server.fullname" . }}-db-migration
      labels:
        {{- include "omero-server.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-omero-sql
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - |
              omero db script -f /scratch/OMERO5.4__0.sql --password {{ include "omero-server.defaultRootPassword" . }}
          volumeMounts:
            - mountPath: /scratch
              name: {{ include "omero-server.fullname" . }}-db-migration-cache
        - name: {{ .Chart.Name }}-db-migration
          image: "postgresql:latest"
          command:
            - |
              psql < /scratch/OMERO5.4__0.sql
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "omero-server.fullname" . }}-db
                  key: PGHOST
                  optional: false
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "omero-server.fullname" . }}-db
                  key: PGPORT
                  optional: false
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "omero-server.fullname" . }}-db
                  key: PGDATBASE
                  optional: false
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ include "omero-server.fullname" . }}-db
                  key: PGUSER
                  optional: false
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "omero-server.fullname" . }}-db
                  key: PGPASSWORD
                  optional: false
          volumeMounts:
            - mountPath: /scratch
              name: {{ include "omero-server.fullname" . }}-db-migration-cache
      volumes:
        - name: {{ include "omero-server.fullname" . }}-config
          configMap:
            name: {{ include "omero-server.fullname" . }}
        - name: {{ include "omero-server.fullname" . }}-secrets
          secret:
            secretName: {{ include "omero-server.fullname" . }}
        - name: {{ include "omero-server.fullname" . }}-db-migration-cache
          emptyDir:
            sizeLimit: 500Mi
