---
# /opt/OMERO.server/etc/grid/config.k8ssecret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omero-server.fullname" . }}-config
  labels:
    {{- include "omero-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.k8ssecret: |
    {{range $k,$v := .Values.config -}}
    {{$k}}={{$v}}
    {{end}}
---
# /.pgpass
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omero-server.fullname" . }}-pgpass
  labels:
    {{- include "omero-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  pgpass: >
    postgresql:5432
    :{{.Values.global.postgresql.auth.database}}
    :{{.Values.global.postgresql.auth.username}}
    :{{.Values.global.postgresql.auth.password}}
