---
# /opt/OMERO.server/etc/grid/config.k8ssecret
# https://docs.openmicroscopy.org/omero/5.6.1/sysadmins/config.html
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omero-server.fullname" . }}
  labels:
    {{- include "omero-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  omero.secret: |
    config set omero.db.host {{ include "omero.postgresql.fullname" . |squote }}
    config set omero.db.name {{ include "omero.postgresql.database" . |squote }}
    config set omero.db.pass {{ include "omero.postgresql.password" . |squote }}
    config set omero.db.port {{ include "omero.postgresql.port" . |squote }}
    config set omero.db.user {{ include "omero.postgresql.username" . |squote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omero-server.fullname" . }}-db
  labels:
    {{- include "omero-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  PGHOST: {{ include "omero.postgresql.fullname" . |quote}}
  PGDATABASE: {{ include "omero.postgresql.database" . |quote}}
  PGPASSWORD: {{ include "omero.postgresql.password" . |quote}}
  PGPORT: {{ include "omero.postgresql.port" . |quote}}
  PGUSER: {{ include "omero.postgresql.username" . |quote}}
---
# /.pgpass
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omero-server.fullname" . }}-pgpass
  labels:
    {{- include "omero-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  pgpass: >
    {{ include "omero.postgresql.fullname" . }}:{{ include "omero.postgresql.port" . }}
    :{{ include "omero.postgresql.database" . }}
    :{{ include "omero.postgresql.username" . }}
    :{{ include "omero.postgresql.password" . }}
