apiVersion: v1
kind: Service
metadata:
  name: {{ include "omero-server.fullname" . }}
  labels:
    {{- include "omero-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ice-router
      protocol: TCP
      name: ice-router
    - port: 4064
      targetPort: ice-router-ssl
      protocol: TCP
      name: ice-router-ssl
  selector:
    {{- include "omero-server.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omero-server.fullname" . }}-hl
  labels:
    {{- include "omero-server.labels" . | nindent 4 }}
spec:
  clusterIP: None
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ice-router
      protocol: TCP
      name: ice-router
    - port: 4064
      targetPort: ice-router-ssl
      protocol: TCP
      name: ice-router-ssl
  selector:
    {{- include "omero-server.selectorLabels" . | nindent 4 }}
