---
# omero/charts/omero-web/templates/configmap.yaml
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omero-web.fullname" . }}
  labels:
    {{- include "omero-web.labels" . | nindent 4 }}
data:
  00kubernetes-configmap.omero: |
{{- with .Values.omero }}
{{- with .web }}
{{- with .application_server }}
    omero.web.application_server.host={{.host}}
    omero.web.application_server.port={{.port}}
{{- end }}
    omero.web.check_version=false
    omero.web.debug={{.debug}}
    omero.web.secure={{.secure}}
    omero.web.server_list=[["omero-omero-server", 4064, "omero"]]
    omero.web.static_url={{.static_url}}
{{- end }}
{{- end }}
