---
# omero/charts/omero-web/templates/configmap.yaml
# https://github.com/ome/omero-iviewer
# omero config set omero.web.wsgi_args ' --limit-request-line 8192'
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omero-web.fullname" . }}
  labels:
    {{- include "omero-web.labels" . | nindent 4 }}
data:
  00kubernetes-configmap.omero: |
    {{- include "omero.config" (dict "omero" .Values.omero "omero_cfg" list) | nindent 4 }}
    {{- if not .Values.omero.web.server_list }}
    omero.web.server_list={{ include "omero-web.server_list" . }}
    {{- end }}
    {{- if .Values.omeroWeb.viewer.iviewer.enabled }}
    omero.web.apps={{ append .Values.omero.web.apps "omero_iviewer" | toJson }}
    omero.web.viewer.view=omero_iviewer.views.index
    {{- if .Values.omeroWeb.viewer.iviewer.open_with_enabled }}
    omero.web.open_with={{ append .Values.omero.web.open_with .Values.omeroWeb.viewer.iviewer.open_with | toJson }}
    {{- end }}
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omero-web.fullname" . }}-nginx
  labels:
    {{- include "omero-web.labels" . | nindent 4 }}
data:
  nginx.conf: |
    pid /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /dev/stdout main;
      error_log   /dev/stderr warn;

      sendfile on;
      keepalive_timeout 65;

      server {
        listen      8080;
        listen      [::]:8080;
        server_name localhost;

        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
          autoindex off;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
          root   /usr/share/nginx/html;
        }
      }
    }
