---
# omero/charts/omero-web/templates/service.yaml
#
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omero-web.fullname" . }}
  labels:
    {{- include "omero-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: omero-web
      protocol: TCP
      name: omero-web
  selector:
    {{- include "omero-web.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omero-web.fullname" . }}-hl
  labels:
    {{- include "omero-web.labels" . | nindent 4 }}
spec:
  clusterIP: None
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: omero-web
      protocol: TCP
      name: omero-web
  selector:
    {{- include "omero-web.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omero-web.fullname" . }}-static
  labels:
    {{- include "omero-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "omero-web.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omero-web.fullname" . }}-static-hl
  labels:
    {{- include "omero-web.labels" . | nindent 4 }}
spec:
  clusterIP: None
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "omero-web.selectorLabels" . | nindent 4 }}
