apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bind.fullname" . }}
  labels:
    {{- include "bind.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
