{{- if not .Values.rndc.key.existingSecret.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bind.fullname" . }}-rndc
  labels:
    {{- include "bind.labels" . | nindent 4 }}
stringData:
  rndc.key: |
    key "rndc-key" {
      algorithm {{ .Values.rndc.key.algorithm }};
      secret {{ .Values.rndc.key.secret | default (randAlphaNum 44) | quote }};
    };
{{- end }}
