apiVersion: v1
kind: Service
metadata:
  name: {{ include "bind.fullname" . }}
  labels:
    {{- include "bind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- .Values.service.ports | toYaml | nindent 4 }}
  selector:
    {{- include "bind.selectorLabels" . | nindent 4 }}
