# Default values for omero.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
## @section Global parameters
## Please, note that this will override the parameters, including dependencies, configured to use the global value
global:
  ## @param global.imageRegistry Global Docker image registryy
  ##
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
  postgresql:
    auth:
      postgresPassword: ""
      username: ""
      password: ""
      database: ""
      existingSecret: ""
      secretKeys:
        adminPasswordKey: ""
        userPasswordKey: ""
        replicationPasswordKey: ""
    existingConfigMap: ""
    configMapKeys:
      PGHOST: ""
      PGHOSTADDR: ""
      PGPORT: ""
      PGDATABASE: ""
      PGUSER: ""
      PGPASSFILE: ""    # https://www.postgresql.org/docs/current/libpq-pgpass.html
    externalIPs: []
    externalName: ""
    ## @param global.postgresql.service.ports.postgresql PostgreSQL service port (overrides `postgresql.service.ports.postgresql`)
    ##
    service:
      ports:
        postgresql: ""

## @section OMERO server parameters
omero-server:
  enabled: true
  omeroDescriptor: "etc/grid/default.xml"
  omeroTargets: "jmx"      # debug|trace

  omeroPrefix: ""
  omeroTmpDir: "/opt/omero/server/omero/tmp"
  omeroDir: "/opt/omero/server/OMERO.server"
  omeroLoadDir: "/omero-config.d"

  omeroData:
    accessMode: ReadWriteMany
    size: 1Gi
    selector: {}  # https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors
    storageClass: ""
  omeroJmx:
    enabled: false

  omeroRootPass: ""

  omeroGlacier2IceSSLExistingSecretName: ""

  # WORKAROUND: omero server log side containers
  omeroLogFiles:
    blitz-0: /opt/omero/server/OMERO.server/var/log/Blitz-0.log
    dropbox: /opt/omero/server/OMERO.server/var/log/DropBox.log
    file-server: /opt/omero/server/OMERO.server/var/log/FileServer.log
    indexer-0: /opt/omero/server/OMERO.server/var/log/Indexer-0.log
    monitor-server: /opt/omero/server/OMERO.server/var/log/MonitorServer.log
    pixel-data-0: /opt/omero/server/OMERO.server/var/log/PixelData-0.log
    processor-0: /opt/omero/server/OMERO.server/var/log/Processor-0.log
    tables-0: /opt/omero/server/OMERO.server/var/log/Tables-0.log
    master-err: /opt/omero/server/OMERO.server/var/log/master.err
    master-out: /opt/omero/server/OMERO.server/var/log/master.out

  ## @section Config parameters (https://docs.openmicroscopy.org/omero/5.6.3/sysadmins/config.html)
  omero:
    # Binary repository
    # @param omero.checksum.supported Checksum algorithms supported by the server for new file uploads
    # @param omero.data.dir
    checksum:
      supported: "SHA1-160,MD5-128,Murmur3-128,Murmur3-32,CRC-32,Adler-32,File-Size-64"
    data:
      dir: "/OMERO"
    # @param omero.fs.repo.path Template for FS managed repository paths
    # @param omero.fs.repo.path_rules Rules to apply to judge the acceptability of FS paths for writing into omero.managed.dir
    fs:
      repo:
        path: "%user%_%userId%//%year%-%month%/%day%/%time%"  # https://docs.openmicroscopy.org/omero/5.6.1/sysadmins/fs-upload-configuration.html
        path_rules: "Windows required,UNIX required"
    # https://doc.zeroc.com/ice/3.6/property-reference/icessl
    # @param omero.glacier2.IceSSL.CAs Specifies the path name of a file containing the certificates of trusted certificate authorities (CAs). The file must be encoded using the PEM format and can contain multiple certificates.
    # @param omero.glacier2.IceSSL.CertFile Specifies a file that contains the program's certificate and the corresponding private key. The file name may be specified relative to the default directory defined by omero.glacier2.IceSSL.DefaultDir.
    # @param omero.glacier2.IceSSL.Ciphers Specifies the cipher suites that IceSSL is allowed to negotiate.
    # @param omero.glacier2.IceSSL.DefaultDir Specifies the default directory in which to look for certificates, key stores, and other files. (default: <omero.data.dir>/certs)
    # @param omero.glacier2.IceSSL.Password Specifies the password necessary to decrypt the private key.
    # @param omero.glacier2.IceSSL.Protocols Specifies the protocols to allow during SSL handshaking. Legal values are SSL3, TLS1, TLS1_0 (alias for TLS1), TLS1_1, and TLS1_2.
    # @param omero.glacier2.IceSSL.ProtocolVersionMax Specifies the maximum protocol to allow during SSL handshaking. Legal values are SSL3, TLS1, TLS1_0 (alias for TLS1), TLS1_1, and TLS1_2.
    glacier2:
      IceSSL:
        CAs: server.pem
        CertFile: server.p12
        Ciphers: HIGH
        DefaultDir: "/OMERO/certs"
        Password: 30263c05-3101-4a4e-8008-a1a46171959e
        ProtocolVersionMax: TLS1_2
        Protocols: TLS1_0,TLS1_1,TLS1_2
        # VerifyPeer: 0
    # @param omero.managed.dir
    # managed:
    #   dir: "${omero.data.dir}/ManagedRepository"
    # https://docs.openmicroscopy.org/omero/5.6.1/sysadmins/config.html#client
    # @param omero.client.browser.thumb_default_size The default thumbnail size
    # @param omero.client.download_as.max_size Clients disable download as jpg/png/tiff above max pixel count
    # @param omero.client.icetransports Comma separated list of Ice transports available to clients
    # @param omero.client.scripts_to_ignore Server-side scripts used in IScript service Clients shouldn’t display
    # @param omero.client.ui.menu.dropdown.colleagues.enabled Flag to show/hide colleagues
    # @param omero.client.ui.menu.dropdown.colleagues.label Client dropdown menu colleagues label
    # @param omero.client.ui.menu.dropdown.everyone.enabled Flag to show/hide all users
    # @param omero.client.ui.menu.dropdown.everyone.label Client dropdown menu all users label
    # @param omero.client.ui.menu.dropdown.leaders.enabled Flag to show/hide leader
    # @param omero.client.ui.menu.dropdown.leaders.label Client dropdown menu leader label
    # @param omero.client.ui.tree.orphans.description Description of the “Orphaned images” container
    # @param omero.client.ui.tree.orphans.enabled Flag to show/hide “Orphaned images” container
    # @param omero.client.ui.tree.orphans.name Name of the “Orphaned images” container located in client tree data manager
    # @param omero.client.ui.tree.type_order Client tree type order rank list first type is ranked 1 (the highest), last is the lowest if set to ‘false’ empty list allows mixing all types and sorting them by default client ordering strategy
    # @param omero.client.viewer.initial_zoom_level Initial client image viewer zoom level for big images
    # @param omero.client.viewer.interpolate_pixels Client viewers interpolate pixels by default
    # @param omero.client.viewer.roi_limit Client viewers roi limit
    # @param omero.client.web.host Absolute omeroweb host http(s)://your_domain/prefix/
    # client:
    #   browser:
    #     thumb_default_size: 96
    #   download_as:
    #     max_size: 144000000
    #   icetransports: "ssl,tcp"
    #   scripts_to_ignore: "/omero/figure_scripts/Movie_Figure.py,/omero/figure_scripts/Split_View_Figure.py,/omero/figure_scripts/Thumbnail_Figure.py,/omero/figure_scripts/ROI_Split_Figure.py,/omero/export_scripts/Make_Movie.py,/omero/import_scripts/Populate_ROI.py"
    #   ui:
    #     menu:
    #       dropdown:
    #         colleagues:
    #           enabled: true
    #           label: "Members"
    #         everyone:
    #           enabled: true
    #           label: "All Members"
    #         leaders:
    #           enabled: true
    #           label: "Owners"
    #     tree:
    #       orphans:
    #         description: "This is a virtual container with orphaned images. These images are not linked anywhere. Just drag them to the selected container."
    #         enabled: true
    #         name: "Orphaned Images"
    #         type_order: "tagset,tag,project,dataset,screen,plate,acquisition,image"
    #   viewer:
    #     initial_zoom_level: 0
    #     interpolate_pixels: true
    #     roi_limit: 2000
    #   web:
    #     host: ""
    # https://docs.openmicroscopy.org/omero/5.6.1/sysadmins/config.html#database
    # @param omero.db.authority The string that will be used as the base for LSIDs in all exported OME objects including OME-XML and OME-TIFF
    # @param omero.db.dialect Implementation of the org.hibernate.dialect.Dialect interface which will be used to convert HQL queries and save operations into SQL SELECTs and DML statements
    # @param omero.db.driver JDBC driver used to access the database
    # @param omero.db.host The host name of the machine on which the database server is running
    # @param omero.db.name The name of the database instance to which OMERO will connect
    # @param omero.db.pass The password to use to connect to the database server
    # @param omero.db.patch The patch version of the database which is in use
    # @param omero.db.poolsize Sets the number of database server connections which will be used by OMERO
    # @param omero.db.port TCP port on which the database server is listening for connections
    # @param omero.db.prepared_statement_cache_size
    # @param omero.db.profile Default values for the current profile will be hard-coded into the hibernate.properties file in the model-*.jar
    # @param omero.db.sql_action_class Implementation of the ome.util.SqlAction interface which will be used to perform all direct SQL actions
    # @param omero.db.statistics Whether JMX statistics are collected for DB usage
    # @param omero.db.user The username to use to connect to the database server
    # @param omero.db.version Version of the database which is in use
    db:
      poolsize: 100
    #  authority: export.openmicroscopy.org
    #  dialect: ome.util.PostgresqlDialect
    #  driver: org.postgresql.Driver
    #  host: localhost
    #  name: omero
    #  pass: omero
    #  patch: 0
    #  port: 5432
    #  prepared_statement_cache_size: 10
    #  profile: psql
    #  sql_action_class: ome.util.actions.PostgresSqlAction
    #  statistics: true
    #  user: omero
    #  version: OMERO5.4
    # @param omero.metrics.bean Which bean to use: nullMetrics does nothing defaultMetrics
    # @param omero.metrics.graphite Address for Metrics to send server data
    # @param omero.metrics.slf4j_minutes Number of minutes to periodically print to slf4j 0 or lower disables the printout
    # metrics:
    #   bean: defaultMetrics
    #   graphite: ""
    #   slf4j_minutes: 60

  replicaCount: 1

  image:
    repository: ghcr.io/sydneyresearchtech/openmicroscopy-omero-server
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: {}
    # prometheus.io/scrape: 'true'
    # prometheus.io/port: '3001'

  podSecurityContext:
    fsGroup: 1000

  securityContext:
    # capabilities:
    #   drop:
    #   - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000

  service:
    type: ClusterIP
    port: 4063

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

## @section OMERO web parameters
omero-web:
  enabled: true

  replicaCount: 1

  image:
    repository: ghcr.io/sydneyresearchtech/openmicroscopy-omero-web
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 4080

  services:
    web:
      type: ClusterIP
      port: 4080
    static:
      type: ClusterIP
      port: 8080

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

service:
  type: ClusterIP
  port: 4080

## @section ingress parameters
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
  host:
    name: chart-example.local
    paths:
      omero-web:
        path: /
        pathType: Prefix
        backend:
          service:
            port:
              number: 4080
      omero-web-static:
        path: /static/
        pathType: Prefix
        backend:
          service:
            port:
              number: 8080
      omero-server-websocket:
        path: /omero-wss/
        pathType: Prefix
        backend:
          service:
            port:
              number: 4066
  tls:
    enabled: false
    secretName: omero-ingress-tls
  #tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

## @section postgresql parameters
## Please reference [PostgreSQL packaged by Bitnami](https://github.com/bitnami/charts/tree/master/bitnami/postgresql/) for more details
##
postgresql:
  enabled: false
