# Default values for omero.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
## @section Global parameters
## Please, note that this will override the parameters, including dependencies, configured to use the global value
global:
  ## @param global.imageRegistry Global Docker image registryy
  ##
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
  postgresql:
    auth:
      postgresPassword: ""
      username: ""
      password: ""
      database: ""
      existingSecret: ""
      secretKeys:
        adminPasswordKey: ""
        userPasswordKey: ""
        replicationPasswordKey: ""
    existingConfigMap: ""
    configMapKeys:
      PGHOST: ""
      PGHOSTADDR: ""
      PGPORT: ""
      PGDATABASE: ""
      PGUSER: ""
      PGPASSFILE: ""    # https://www.postgresql.org/docs/current/libpq-pgpass.html
    externalIPs: []
    externalName: ""
    ## @param global.postgresql.service.ports.postgresql PostgreSQL service port (overrides `postgresql.service.ports.postgresql`)
    ##
    service:
      ports:
        postgresql: ""

omero-server:
  enabled: true

omero-web:
  enabled: true

## @section postgresql parameters
## Please reference [PostgreSQL packaged by Bitnami](https://github.com/bitnami/charts/tree/master/bitnami/postgresql/) for more details
##
postgresql:
  enabled: false
