# Default values for omero.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
## @section Global parameters
## Please, note that this will override the parameters, including dependencies, configured to use the global value
global:
  ## @param global.imageRegistry Global Docker image registryy
  ##
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
  postgresql:
    auth:
      postgresPassword: ""
      username: "omero"
      password: "omero"
      database: "omero"
      existingSecret: ""
      secretKeys:
        adminPasswordKey: ""
        userPasswordKey: ""
        replicationPasswordKey: ""
    ## @param global.postgresql.service.ports.postgresql PostgreSQL service port (overrides `service.ports.postgresql`)
    ##
  service:
    ports:
      postgresql: ""

omero-server:
  enabled: true

omero-web:
  enabled: true

## @section postgresql parameters
## Please reference [PostgreSQL packaged by Bitnami](https://github.com/bitnami/charts/tree/master/bitnami/postgresql/) for more details
##
postgresql:
  enabled: true
