apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nvflare.server.fullname" . }}-startup
  labels:
    {{- include "nvflare.labels" . | nindent 4 }}
data:
  fed_server.json: |
    {{- tpl (.Files.Get "tpl/server/startup/fed_server.json") . | fromJson | toPrettyJson | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nvflare.server.fullname" . }}-local
  labels:
    {{- include "nvflare.labels" . | nindent 4 }}
data:
  authorization.json: |
    {{- tpl (.Files.Get "tpl/server/local/authorization.json") . | fromJson | toPrettyJson | nindent 4 }}
  log_config.json: |
    {{- tpl (.Files.Get "tpl/server/local/log_config.json") . | nindent 4 }}
  resources.json: |
    {{- tpl (.Files.Get "tpl/server/local/resources.json") . | fromJson | toPrettyJson | nindent 4 }}
