apiVersion: v1
kind: Service
metadata:
  name: {{ include "nvflare.server.fullname" . }}
  labels:
    {{- include "nvflare.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.fl.port }}
      targetPort: fl
      protocol: TCP
      name: fl
    - port: {{ .Values.server.service.admin.port }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "nvflare.server.selectorLabels" . | nindent 4 }}
