apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mirc-ctp.fullname" . }}
  labels:
    {{- include "mirc-ctp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mirc-ctp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
      labels:
        {{- include "mirc-ctp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mirc-ctp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.Configuration.Pipeline -}}
          {{- range $i,$p := .Values.Configuration.Pipeline }}
              {{- range $k,$v := $p }}
                {{- if and (kindIs "map" $v) (hasKey $v "@port") }}
            - name: {{ lower $k |trunc 13 }}-{{ $i }}
              containerPort: {{ index $v "@port" }}
              protocol: TCP
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            {{- if eq "yes" (index .Values.Configuration.Server "@ssl") }}
              scheme: HTTPS
            {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            {{- if eq "yes" (index .Values.Configuration.Server "@ssl") }}
              scheme: HTTPS
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /JavaPrograms/CTP/CACHE
              name: cache
            - mountPath: /JavaPrograms/CTP/logs
              name: logs
            - mountPath: /JavaPrograms/config
              name: config
              readOnly: true
          {{- range $name,$p := .Values.persistence }}
            - mountPath: {{ $p.mountPath |quote }}
              name: {{ $name }}-pvc
          {{- end }}
          {{- if .Values.ssl_certs.secretName }}
            - mountPath: /k8s-certs
              name: k8s-certs
              readOnly: true
          {{- end }}
        - name: ctp-log
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: busybox
          command: ["sh","-c"]
          args:
            - |
              exec tail -F -n 1000 "${LOG_FILE}"
          env:
            - {name: LOG_FILE, value: /JavaPrograms/CTP/logs/ctp.log}
          volumeMounts:
            - mountPath: /JavaPrograms/CTP/logs
              name: logs
              readOnly: true
      initContainers:
        - name: copy
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ['sh','-c']
          args:
            - |
              set -x
              cp /JavaPrograms/config/* /config/
          volumeMounts:
            - mountPath: /config
              name: config
        - name: config
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: ghcr.io/sydneyresearchtech/python:alpine3.18
          env:
            - {name: PKCS12, value: "/config/cert-chain.p12"}
          command: ['sh','-c']
          args:
            - |
              set -x
              [ -f /k8s-config/config.yaml ] && yaml2xml /k8s-config/config.yaml /config/config.xml ||:
              [ -f /k8s-config/users.yaml ] && yaml2xml /k8s-config/users.yaml /config/users.xml ||:
              # openssl pkcs12 -in <> -inkey <> -out "${PKCS12}" -legacy -export -chain
              # keytool -importcert -noprompt -alias ctp -file "${PKCS12}" -keystore /config/k8s-keystore -storepass ctpstore -storetype pkcs12 -providername SUN
          volumeMounts:
            - mountPath: /k8s-config
              name: config-yaml
              readOnly: true
            - mountPath: /config
              name: config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: cache
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: config
          emptyDir: {}
        - name: config-yaml
          configMap:
            name: {{ include "mirc-ctp.fullname" . }}
      {{- range $name,$p := .Values.persistence }}
        - name: {{ $name }}-pvc
          persistentVolumeClaim:
            claimName: {{ default (printf "%s-%s" (include "mirc-ctp.fullname" $) $name) $p.existingClaim }}
      {{- end }}
      {{- if .Values.ssl_certs.secretName }}
        - name: k8s-certs
          secret:
            secretName: {{ .Values.ssl_certs.secretName }}
      {{- end }}
