apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-server
  labels:
    app.kubernetes.io/name: iperf3-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: iperf3-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iperf3-server
    spec:
      containers:
      - name: iperf3-server
        image: ghcr.io/sydneyresearchtech/diagnostics:0.1.0
        env:
        - {name: IPERF_PORT, value: 5201}
        command: ["iperf3"]
        args:
        - -p $IPERF_PORT
        - --server
        - --debug
        ports:
        - containerPort: 5201
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-server
  annotations: {}
  #  service.beta.kubernetes.io/load-balancer-source-ranges: 129.78.0.0/16,203.32.106.0/24,203.32.107.0/24,220.235.127.71/32
spec:
  selector:
    app.kubernetes.io/name: iperf3-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5201
      targetPort: 5201
  loadBalancerSourceRanges:
  - 129.78.0.0/16
  - 203.32.106.0/24
  - 203.32.107.0/24
  - 220.235.127.71/32
