{{- if false -}}
{{- if .Values.master.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "cryosparc.fullname" . }}-verify-extensive-workflow"
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 8 }}
  containers:
    - name: cryosparcm
      image: "{{ .Values.master.image.repository }}:{{ .Values.master.image.tag | default .Chart.AppVersion }}"
      command: ['bash','-c']
      env:
        - {name: TERM, value: xterm}
      args:
        - |
          ERROR=0
          eval $(/cryosparc_master/bin/cryosparcm env)
          USER_ID=$(cryosparcm listusers \
            |sed -e '1,2d' -e 's/\s//g' -e '/^\s*$/d' \
              -e '{{ .Values.master.service_account.username }}' \
            |cut -d| -f4)
          cryosparcm cli 'create_empty_project(owner_user_id: "", project_container_dir: "/cryosparc_project")'
          exit $ERROR
      volumeMounts:
        {{- include "cryosparc.master.volumeMounts" . |nindent 12 }}
  restartPolicy: Never
  volumes:
    {{- include "cryosparc.master.volumes" . |nindent 8 }}
{{- end }}
{{- end }}
