# Default values for cryosparcw.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# hostname of the worker node to connect to your cryoSPARC instance
hostname: ""
# hostname of the server where the master is installed on
master: "cryosparcm"
# base port number for the cryoSPARC instance you are connecting the worker node to
port: 39000
# path to directory on local SSD if "" --nossd parameter will apply
ssd_path: ""
# use when updating and existing configuration
update: false
# custom SSH connection string such as user@hostname
ssh_string: ""
# enable this number of CPU cores; 0 uses all cpu cores
cpus: 0
# connect worker with no GPUs
nogpu: false
# enable specific GPU devices only, e.g. gpus: 0,1,2,3
# For advanced configuration, run the gpulist command
# cryosparcw gpulist
gpus: ""
# quota of how much SSD space to use (MB); 0 = no quota
ssd_quota: 0
# minimum free space to leave on SSD (MB); 0 = no reserve
ssd_reseved: 0
# name of lane to add worker to
lane: ""
# force creation of a new lane if the lane specified does not exist
new_lane: false

ssh_secret:
  name: "cryosparc-user"
  key: "ssh-publickey"

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 2222

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
