apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryosparc.fullname" . }}w
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
stringData:
  config.sh: |
    # {{ .Template.Name }}
    export CRYOSPARC_LICENSE_ID="{{ .Values.license_id }}"
    export CRYOSPARC_USE_GPU=true
    export CRYOSPARC_TIFF_IO_SHM=false
