apiVersion: v1
kind: Service
metadata:
  name: {{ include "cryosparc.fullname" . }}w
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.worker.workload_resource "StatefulSet" }}
  clusterIP: None
  {{- end }}
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: sshd
      protocol: TCP
      name: sshd
  selector:
    {{- include "cryosparc.w.selectorLabels" . | nindent 4 }}
