apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orthanc.fullname" . }}
  labels:
    {{- include "orthanc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "orthanc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orthanc.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "orthanc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          # image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          image: {{ include "orthanc.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - {name: GENERATE_HOST_ID_IF_MISSING, value: "false"}
            - {name: VERBOSE_STARTUP, value: {{ .Values.verbose_startup | quote }}}
            - {name: VERBOSE_ENABLED, value: {{ .Values.verbose_enabled | quote }}}
            - {name: TRACE_ENABLED, value: {{ .Values.trace_enabled | quote }}}
            - {name: NO_JOBS, value: {{ .Values.no_jobs | quote }}}
            - {name: MALLOC_ARENA_MAX, value: {{ .Values.malloc_arena_max | quote }}}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /usr/share/orthanc/plugins
              name: plugins-enabled
            - mountPath: /tmp
              name: tmpd
            - mountPath: /etc/orthanc
              name: orthanc-config
              readOnly: true
            - mountPath: /.k8s/secrets
              name: orthanc-secrets
              readOnly: true
            # - mountPath: /var/lib/orthanc/db
            #   name: storage
            - mountPath: {{ .Values.storageDirectory.path }}
              name: storage
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: plugins-enabled
          emptyDir: {}
        - name: tmpd
          emptyDir: {}
        - name: orthanc-config
          configMap:
            name: {{ include "orthanc.fullname" . }}
        - name: orthanc-secrets
          secret:
            secretName: {{ include "orthanc.fullname" . }}
        - name: index-directory
          emptyDir: {}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.storageDirectory.existingVolumeClaim | default (printf "%s-%s" (include "orthanc.fullname" .) "storage") }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
