{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "(include 'orthanc.fullname' .)-postgresql") | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $password := (get $secretData "password") | default (randAlphaNum 32 | b64enc) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orthanc.fullname" . }}
  labels:
    {{- include "orthanc.labels" . | nindent 4 }}
data:
  postgresql.json: {{ tpl (.Files.Get "conf/postgresql.json") (set . "PGPASSWORD" ($password | b64dec)) | b64enc | quote }}
---
# https://www.postgresql.org/docs/current/libpq-pgpass.html
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orthanc.fullname" . }}-pgpass
  labels:
    {{- include "orthanc.labels" . | nindent 4 }}
data:
  pgpass: {{
    print .Values.PostgreSQL.Host ":" .Values.PostgreSQL.Port ":" .Values.PostgreSQL.Database ":"
    print .Values.PostgreSQL.Username ":" $password
    | b64enc | quote
  }}
{{- if and .Values.postgresql.enabled
       (or .Values.global.postgresql.auth.existingSecret .Values.postgresql.auth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orthanc.fullname" . }}-postgresql
  labels:
    {{- include "orthanc.labels" . | nindent 4 }}
data:
  {{- $pgpassword := (get $secretData "postgres-password") | default (randAlphaNum 32 | b64enc) }}
  postgres-password: {{ $pgpassword | quote }}
  password: {{ $password | quote }}
{{- end }}
